"""fix user model add flse to columns in table

Revision ID: fdfb1b71b390
Revises: 7ecfbe4f372c
Create Date: 2024-04-15 18:52:20.589221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdfb1b71b390'
down_revision: Union[str, None] = '7ecfbe4f372c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False,
               type_=sa.String(length=128))
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False,
               type_=sa.String(length=128))
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False,
               type_=sa.String(length=128))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
