"""deleted column token from user table

Revision ID: c226fe01933d
Revises: 0c24d90e6076
Create Date: 2024-04-22 11:38:24.452042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c226fe01933d'
down_revision: Union[str, None] = '0c24d90e6076'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_token_key', 'users', type_='unique')
    op.drop_column('users', 'token')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('token', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    op.create_unique_constraint('users_token_key', 'users', ['token'])
    # ### end Alembic commands ###
