"""Use visability for column table

Revision ID: a8650e4297f4
Revises: 75d38ccd38a3
Create Date: 2024-04-27 13:32:17.030321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a8650e4297f4'
down_revision: Union[str, None] = '75d38ccd38a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('companies', 'visibility',
                    existing_type=sa.VARCHAR(length=10),
                    type_=postgresql.ENUM('PUBLIC', 'PRIVATE', name='visibility'),
                    existing_nullable=False,
                    postgresql_using="visibility::visibility"
    )
    op.drop_index('ix_companies_company_name', table_name='companies')
    op.create_index(op.f('ix_companies_company_name'), 'companies', ['company_name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_companies_company_name'), table_name='companies')
    op.create_index('ix_companies_company_name', 'companies', ['company_name'], unique=False)
    op.alter_column('companies', 'visibility',
               existing_type=postgresql.ENUM('PUBLIC', 'PRIVATE', name='visibility'),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    # ### end Alembic commands ###
