"""Uniqueue name company

Revision ID: 75a2f1fdb7a9
Revises: 75d38ccd38a3
Create Date: 2024-04-26 16:09:18.883600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75a2f1fdb7a9'
down_revision: Union[str, None] = '75d38ccd38a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_companies_company_name', table_name='companies')
    op.create_index(op.f('ix_companies_company_name'), 'companies', ['company_name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_companies_company_name'), table_name='companies')
    op.create_index('ix_companies_company_name', 'companies', ['company_name'], unique=False)
    # ### end Alembic commands ###
