"""Add Invite column

Revision ID: 9303fbc7bc3f
Revises: 587b4bd5f4a0
Create Date: 2024-04-30 12:06:59.341919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9303fbc7bc3f'
down_revision: Union[str, None] = '587b4bd5f4a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invites',
    sa.Column('invite_from', sa.Integer(), nullable=False),
    sa.Column('invite_to', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('status', postgresql.ENUM('INVITE', 'REQUEST', name='invitestatusenum'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['invite_from'], ['users.id'], ),
    sa.ForeignKeyConstraint(['invite_to'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invites_id'), 'invites', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invites_id'), table_name='invites')
    op.drop_table('invites')
    # ### end Alembic commands ###
