"""add type invite column

Revision ID: a6eae76accd7
Revises: 9303fbc7bc3f
Create Date: 2024-05-01 14:01:23.720294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a6eae76accd7'
down_revision: Union[str, None] = '9303fbc7bc3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('company_members_company_id_fkey', 'company_members', type_='foreignkey')
    op.drop_constraint('company_members_user_id_fkey', 'company_members', type_='foreignkey')
    op.create_foreign_key(None, 'company_members', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'company_members', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.add_column('invites', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('invites', sa.Column('type_invite', postgresql.ENUM('INVITE', 'REQUEST', name='invitetypeenum'), nullable=False))
    op.drop_constraint('invites_invite_to_fkey', 'invites', type_='foreignkey')
    op.drop_constraint('invites_company_id_fkey', 'invites', type_='foreignkey')
    op.drop_constraint('invites_invite_from_fkey', 'invites', type_='foreignkey')
    op.create_foreign_key(None, 'invites', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'invites', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.drop_column('invites', 'invite_to')
    op.drop_column('invites', 'invite_from')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invites', sa.Column('invite_from', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('invites', sa.Column('invite_to', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'invites', type_='foreignkey')
    op.drop_constraint(None, 'invites', type_='foreignkey')
    op.create_foreign_key('invites_invite_from_fkey', 'invites', 'users', ['invite_from'], ['id'])
    op.create_foreign_key('invites_company_id_fkey', 'invites', 'companies', ['company_id'], ['id'])
    op.create_foreign_key('invites_invite_to_fkey', 'invites', 'users', ['invite_to'], ['id'])
    op.drop_column('invites', 'type_invite')
    op.drop_column('invites', 'user_id')
    op.drop_constraint(None, 'company_members', type_='foreignkey')
    op.drop_constraint(None, 'company_members', type_='foreignkey')
    op.create_foreign_key('company_members_user_id_fkey', 'company_members', 'users', ['user_id'], ['id'])
    op.create_foreign_key('company_members_company_id_fkey', 'company_members', 'companies', ['company_id'], ['id'])
    # ### end Alembic commands ###
